######################################################################
# Automatically generated by qmake (3.1) Sun Apr 21 15:23:14 2019
######################################################################

TEMPLATE = subdirs
SUBDIRS += \
        Application/Plugins/vsdt/lab/work \
        Application

CONFIG += ordered
